# Use root/example as user/password credentials
version: '3.1'

services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: never
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  phpmyadimn:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:8081

